export default{
    
    cardPool: [ 'gentryOfHermitage2','theHeronsCourt','tapestryOfGoldenFlames', 'wanyee'],

    defaultResult: {
        star5: [ 
            [ 'character', '5', 'Keqing', 'electric', '刻晴' ],
            [ 'character', '5', 'Qiqi', 'ice', '七七' ],
            [ 'character', '5', 'Mona', 'water', '莫娜' ],
            [ 'character', '5', 'Diluc', 'fire', '迪卢克' ],
            [ 'character', '5', 'Jean', 'wind', '琴' ],
         ],
        star4: [ 
            [ 'character', '4', 'Yunjin', 'stone', '云堇' ],
            [ 'character', '4', 'Gorou', 'stone', '五郎' ],
            [ 'character', '4', 'Thoma', 'fire', '托马' ],
            [ 'character', '4', 'Sara', 'electric', '九条裟罗' ],
            [ 'character', '4', 'Sayu', 'wind', '早柚' ],
            [ 'character', '4', 'Yanfei', 'fire', '烟绯' ],
            [ 'character', '4', 'Rosaria', 'ice', '罗莎莉亚' ],
            [ 'character', '4', 'Xinyan', 'fire', '辛焱' ],
            [ 'character', '4', 'Diona', 'ice', '迪奥娜' ],
            [ 'character', '4', 'Sucrose', 'wind', '砂糖' ],
            [ 'character', '4', 'Chongyun', 'ice', '重云' ],
            [ 'character', '4', 'Noelle', 'stone', '诺艾尔' ],
            [ 'character', '4', 'Bennett', 'fire', '班尼特' ],
            [ 'character', '4', 'Fischl', 'electric', '菲谢尔' ],
            [ 'character', '4', 'Ningguang', 'stone', '凝光' ],
            [ 'character', '4', 'Xingqiu', 'water', '行秋' ],
            [ 'character', '4', 'Beidou', 'electric', '北斗' ],
            [ 'character', '4', 'Xiangling', 'fire', '香菱' ],
            [ 'character', '4', 'Razor', 'electric', '雷泽' ],
            [ 'character', '4', 'Barbara', 'water', '芭芭拉' ],
            
            [ 'weapon', '4', 'Favonius_Sword', 'sword', '西风剑' ],
            [ 'weapon', '4', 'The_Flute', 'sword', '笛剑' ],
            [ 'weapon', '4', 'Sacrificial_Sword', 'sword', '祭礼剑' ],
            [ 'weapon', '4', 'Lion\'s_Roar', 'sword', '匣里龙吟' ],
            [ 'weapon', '4', 'Favonius_Greatsword', 'claymore', '西风大剑' ],
            [ 'weapon', '4', 'The_Bell', 'claymore', '钟剑' ],
            [ 'weapon', '4', 'Sacrificial_Greatsword', 'claymore', '祭礼大剑' ],
            [ 'weapon', '4', 'Rainslasher', 'claymore', '雨裁' ],
            [ 'weapon', '4', 'Dragon\'s_Bane', 'pike', '匣里灭辰' ],
            [ 'weapon', '4', 'Favonius_Lance', 'pike', '西风长枪' ],
            [ 'weapon', '4', 'Favonius_Codex', 'magic', '西风秘典' ],
            [ 'weapon', '4', 'The_Widsith', 'magic', '流浪乐章' ],
            [ 'weapon', '4', 'Sacrificial_Fragments', 'magic', '祭礼残章' ],
            [ 'weapon', '4', 'Mappa_Mare', 'magic', '万国诸海图谱' ],
            [ 'weapon', '4', 'Eye_of_Perception', 'magic', '昭心' ],
            [ 'weapon', '4', 'Favonius_Warbow', 'bow', '西风猎弓' ],
            [ 'weapon', '4', 'The_Stringless', 'bow', '绝弦' ],
            [ 'weapon', '4', 'Sacrificial_Bow', 'bow', '祭礼弓' ],
            [ 'weapon', '4', 'Rust', 'bow', '弓藏' ],
            [ 'weapon', '4', 'Mouun\'s_Moon', 'bow', '曚云之月' ],
         ],
        star3: [ 
            [ 'weapon', '3', 'Cool_Steel', 'sword', '冷刃' ],
            [ 'weapon', '3', 'Harbinger_of_Dawn', 'sword', '黎明神剑' ],
            [ 'weapon', '3', 'Traveler\'s_Handy_Sword', 'sword', '旅行剑' ],
            [ 'weapon', '3', 'Fillet_Blade', 'sword', '吃虎鱼刀' ],
            [ 'weapon', '3', 'Skyrider_Sword', 'sword', '飞天御剑' ],
            [ 'weapon', '3', 'Ferrous_Shadow', 'sword', '铁影阔剑' ],
            [ 'weapon', '3', 'Bloodtainted_Greatsword', 'claymore', '沐浴龙血的剑' ],
            [ 'weapon', '3', 'White_Iron_Greatsword', 'claymore', '白铁大剑' ],
            [ 'weapon', '3', 'Debate_Club', 'claymore', '以理服人' ],
            [ 'weapon', '3', 'Skyrider_Greatsword', 'claymore', '飞天大御剑' ],
            [ 'weapon', '3', 'White_Tassel', 'pike', '白缨枪' ],
            [ 'weapon', '3', 'Halberd', 'pike', '钺矛' ],
            [ 'weapon', '3', 'Black_Tassel', 'pike', '黑缨枪' ],
            [ 'weapon', '3', 'Magic_Guide', 'magic', '魔导绪论' ],
            [ 'weapon', '3', 'Thrilling_Tales_of_Dragon_Slayers', 'magic', '讨龙英杰谭' ],
            [ 'weapon', '3', 'Otherworldly_Story', 'magic', '异世界行记' ],
            [ 'weapon', '3', 'Emerald_Orb', 'magic', '翡玉法球' ],
            [ 'weapon', '3', 'Twin_Nephrite', 'magic', '甲级玉珏' ],
            [ 'weapon', '3', 'Raven_Bow', 'bow', '鸦羽弓' ],
            [ 'weapon', '3', 'Sharpshooter\'s_Oath', 'bow', '神射手之誓' ],
            [ 'weapon', '3', 'Recurve_Bow', 'bow', '反曲弓' ],
            [ 'weapon', '3', 'Slingshot', 'bow', '弹弓' ],
            [ 'weapon', '3', 'Messenger', 'bow', '信使' ],
         ]
    },
    colors: {
        fire: 'EE4828',
        water: '478ECE',
        wind: '42A4A4',
        electric: '6A5ABF',
        grass: '',
        ice: '19ABCB',
        stone: 'CF8F4B',
        weapon: 'EF7C1C',
        always: '757CC8'
    }
}